export const UPDATE_MAP = 'UPDATE_MAP'
export const INIT_MAP = 'INIT_MAP'
export const RANDOM_MAP = 'RANDOM_MAP'
export const TOGGLE_SEED = 'TOGGLE_SEED'
export const DISABLE_EDIT = 'DISABLE_EDIT'
export const ENABLE_EDIT = 'ENABLE_EDIT'
